add 'executorService.shutdown()' call to 'Server.stop()'
teragrep/rlp_03 pull request #73
Opened 2024-02-21 13:30 UTC by eemhu

Fix for issue #59

2024-02-21 14:57 UTC, kortemik commented
this is actually already present in SocketPoll.close()

2024-02-21 15:02 UTC, kortemik commented
i think the appropriate place would be after 
```
            while (!stop.get()) {
                socketPoll.poll();
            }
```
because socketPoll use the factory and there might be an active poll in progress and therefore it wouldn't close cleanly.

2024-02-22 12:40 UTC, kortemik requested changes

2024-02-22 12:40 UTC, kortemik commented on src/main/java/com/teragrep/rlp_03/Server.java
> +            executorService.shutdown();
actually when rethinking the finally {} might be even more appropriate so the executorService would be closed even if socketPoll throws

2024-03-01 10:23 UTC, kortemik approved these changes

2024-03-06 12:52 UTC, kortemik commented
needs rebase

2024-03-06 13:45 UTC, eemhu commented
rebased on newest main branch.

2024-03-07 10:00 UTC, merged