Adds rlp_09 manual benchmarking test for multiple input/output thread combinations
teragrep/rlp_03 pull request #83
Opened 2024-02-28 08:28 UTC by StrongestNumber9

~~WIP: rlp_09 requires the librarized version, do not merge before that is done and updated~~

Allows running automatic benchmarks for asymmetric input:output thread counts. The messages sent and received *SHOULD* always be the same here but both are printed for consistency reasons

```sh
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <2> server and <2> input threads test for <60> seconds
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest -                Flooder        Server
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Threads        2              2
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Records        2,399,186      2,399,186
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - RPS            39,986         39,986
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - RPS/thread     19,993         19,993
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <4> server and <4> input threads test for <60> seconds
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest -                Flooder        Server
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Threads        4              4
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Records        4,263,760      4,263,760
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - RPS            71,062         71,062
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - RPS/thread     17,765         17,765
```

2024-02-28 17:30 UTC, kortemik commented
use records per second rps instead of eps. document this rule into strac,
next to folder/directory naming rule.

ke 28. helmik. 2024 klo 10.28 Strongest Number 9 ***@***.***>
kirjoitti:

> WIP: rlp_09 requires the librarized version, do not merge before that is
> done and updated
> WIP: Output printing requires quite a lot of tuning
>
> Allows running automatic benchmarks for asymmetric input:output thread
> counts
>
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <1> server and <1> input threads test for <60> seconds
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Sent <1339811> messages with <1> threads (22330 EPS / 22330 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Received <1339811> messages with <1> threads (22330 EPS / 22330 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <2> server and <2> input threads test for <60> seconds
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Sent <2510186> messages with <2> threads (41836 EPS / 20918 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Received <2510186> messages with <2> threads (41836 EPS / 20918 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <4> server and <4> input threads test for <60> seconds
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Sent <4451659> messages with <4> threads (74194 EPS / 18548 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Received <4451659> messages with <4> threads (74194 EPS / 18548 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <8> server and <8> input threads test for <60> seconds
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Sent <6470393> messages with <8> threads (107839 EPS / 13479 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Received <6470393> messages with <8> threads (107839 EPS / 13479 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <1> server and <4> input threads test for <60> seconds
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Sent <1283741> messages with <1> threads (21395 EPS / 21395 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Received <1283741> messages with <4> threads (21395 EPS / 5348 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <4> server and <1> input threads test for <60> seconds
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Sent <3580718> messages with <4> threads (59678 EPS / 14919 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Received <3580718> messages with <1> threads (59678 EPS / 59678 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <2> server and <4> input threads test for <60> seconds
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Sent <2452397> messages with <2> threads (40873 EPS / 20436 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Received <2452397> messages with <4> threads (40873 EPS / 10218 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <4> server and <2> input threads test for <60> seconds
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Sent <4336596> messages with <4> threads (72276 EPS / 18069 per thread)
> [main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Received <4336596> messages with <2> threads (72276 EPS / 36138 per thread)
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/teragrep/rlp_03/pull/83
> Commit Summary
>
>    - 1c68f0f
>    <https://github.com/teragrep/rlp_03/pull/83/commits/1c68f0f1e661670572856e3266c36ccb441ef497>
>    Adds rlp_09 manual benchmarking test
>
> File Changes
>
> (2 files <https://github.com/teragrep/rlp_03/pull/83/files>)
>
>    - *M* pom.xml
>    <https://github.com/teragrep/rlp_03/pull/83/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8>
>    (12)
>    - *A* src/test/java/com/teragrep/rlp_03/ManualBenchmarkTest.java
>    <https://github.com/teragrep/rlp_03/pull/83/files#diff-1f3d0845daa429f8a863deea085ccc057e64d019901ebff098aca438626e4f9f>
>    (119)
>
> Patch Links:
>
>    - https://github.com/teragrep/rlp_03/pull/83.patch
>    - https://github.com/teragrep/rlp_03/pull/83.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/teragrep/rlp_03/pull/83>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGX2OTLZTDKNXCDT6LH5YTYV3TCFAVCNFSM6AAAAABD5RZMUOVHI2DSMVQWIX3LMV43ASLTON2WKOZSGE2TQMZYG4ZTIOA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-02-29 08:12 UTC, StrongestNumber9 commented
Uses records instead of events now

2024-02-29 13:02 UTC, StrongestNumber9 commented
Current output format is

```sh
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <4> server and <4> input threads test for <60> seconds
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest -                Flooder        Server
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Threads        4              4
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Records        4,443,582      4,443,582
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Megabytes      271.21         271.21
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Megabytes/s    4.52           4.52
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - RPS            74,059         74,059
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - RPS/thread     18,514         18,514
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Running <8> server and <8> input threads test for <60> seconds
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest -                Flooder        Server
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Threads        8              8
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Records        6,542,725      6,542,725
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Megabytes      399.34         399.34
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - Megabytes/s    6.66           6.66
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - RPS            109,045        109,045
[main] INFO com.teragrep.rlp_03.ManualBenchmarkTest - RPS/thread     13,630         13,630
```

Anything to add/change?

2024-03-07 11:47 UTC, kortemik requested changes

2024-03-07 11:47 UTC, kortemik commented on pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
snapshot version in use, this will not compile in CI?

2024-03-11 07:26 UTC, StrongestNumber9 commented
Added proper rlp_09 version, should be good for re-reviewing and merging

2024-03-11 07:29 UTC, StrongestNumber9 commented
rlp_09 supports specific per-thread records/bytes sent, are those interesting to implement or is calculating average throughput enough?

2024-03-11 07:49 UTC, eemhu approved these changes
Looks good to me!

2024-03-11 15:21 UTC, kortemik approved these changes

2024-03-11 15:21 UTC, merged